export const MODELOS_IA_CONTRATO = [
  {
    id: 'multi-models',
    nome: 'Multi-models',
    descricao: 'Gemini gera e GPT revisa, com fallback automatico',
    precoInput: '-',
    precoOutput: '-',
    precoLabel: 'Custo combinado variavel',
    limiteDiario: 1,
  },
  {
    id: 'gemini-2.0-flash',
    nome: 'Gemini 2.0 Flash',
    descricao: 'Rapido para gerar rascunho inicial',
    precoInput: '$0,10',
    precoOutput: '$0,40',
    precoLabel: '~$0,10-0,40 / 1M tokens',
    limiteDiario: 3,
  },
  {
    id: 'gpt-5-nano',
    nome: 'GPT-5 Nano',
    descricao: 'Mais rápido e econômico',
    precoInput: '$0,05',
    precoOutput: '$0,40',
    precoLabel: '~$0,05-0,40 / 1M tokens',
    limiteDiario: 3,
  },
  {
    id: 'gpt-5-mini',
    nome: 'GPT-5 Mini',
    descricao: 'Melhor custo-benefício',
    precoInput: '$0,25',
    precoOutput: '$2,00',
    precoLabel: '~$0,25-2,00 / 1M tokens',
    limiteDiario: 1,
  },
  {
    id: 'gpt-5.4',
    nome: 'GPT-5.4',
    descricao: 'Máxima qualidade',
    precoInput: '$2,50',
    precoOutput: '$15,00',
    precoLabel: '~$2,50-15,00 / 1M tokens',
    limiteDiario: 1,
  },
] as const
