import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react';
import { forwardRef } from 'react';
import * as OutlineIcons from '@heroicons/react/24/outline';
import * as SolidIcons from '@heroicons/react/24/solid';

export type LucideProps = SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string; absoluteStrokeWidth?: boolean };

export type LucideIcon = ForwardRefExoticComponent<LucideProps & RefAttributes<SVGSVGElement>>;

function createIcon(heroName: string): LucideIcon {
  const Hero = (OutlineIcons as Record<string, any>)[heroName] ?? (SolidIcons as Record<string, any>)[heroName] ?? OutlineIcons.QuestionMarkCircleIcon;
  return forwardRef<SVGSVGElement, LucideProps>(function Icon({ size = 24, strokeWidth: _strokeWidth, absoluteStrokeWidth: _absoluteStrokeWidth, style, ...props }, ref) {
    return <Hero ref={ref} style={{ width: size, height: size, ...style }} {...props} />;
  });
}

export const AlertCircle = createIcon('ExclamationCircleIcon');
export const AlertTriangle = createIcon('ExclamationTriangleIcon');
export const ArrowDownCircle = createIcon('ArrowDownCircleIcon');
export const ArrowLeft = createIcon('ArrowLeftIcon');
export const ArrowRight = createIcon('ArrowRightIcon');
export const ArrowUpCircle = createIcon('ArrowUpCircleIcon');
export const BadgeDollarSign = createIcon('CurrencyDollarIcon');
export const BarChart3 = createIcon('ChartBarIcon');
export const Bell = createIcon('BellIcon');
export const Box = createIcon('ArchiveBoxIcon');
export const Briefcase = createIcon('BriefcaseIcon');
export const Building = createIcon('BuildingOfficeIcon');
export const Building2 = createIcon('BuildingOffice2Icon');
export const Calendar = createIcon('CalendarDaysIcon');
export const Check = createIcon('CheckIcon');
export const CheckCircle2 = createIcon('CheckCircleIcon');
export const CheckSquare = createIcon('CheckBadgeIcon');
export const ChevronDown = createIcon('ChevronDownIcon');
export const ChevronLeft = createIcon('ChevronLeftIcon');
export const ChevronRight = createIcon('ChevronRightIcon');
export const ChevronUp = createIcon('ChevronUpIcon');
export const ChevronsLeft = createIcon('BackwardIcon');
export const ChevronsRight = createIcon('ForwardIcon');
export const ClipboardList = createIcon('ClipboardDocumentListIcon');
export const Clock = createIcon('ClockIcon');
export const Clock3 = createIcon('ClockIcon');
export const Compass = createIcon('CompassIcon');
export const CreditCard = createIcon('CreditCardIcon');
export const Database = createIcon('CircleStackIcon');
export const DocumentDuplicate = createIcon('DocumentDuplicateIcon');
export const DollarSign = createIcon('CurrencyDollarIcon');
export const Download = createIcon('ArrowDownTrayIcon');
export const Edit2 = createIcon('PencilSquareIcon');
export const Eye = createIcon('EyeIcon');
export const FileSpreadsheet = createIcon('TableCellsIcon');
export const FileText = createIcon('DocumentTextIcon');
export const Filter = createIcon('FunnelIcon');
export const FilterX = createIcon('FunnelIcon');
export const Flame = createIcon('FireIcon');
export const Folder = createIcon('FolderIcon');
export const Hash = createIcon('HashtagIcon');
export const History = createIcon('ClockIcon');
export const Info = createIcon('InformationCircleIcon');
export const Instagram = createIcon('CameraIcon');
export const Layers = createIcon('Squares2X2Icon');
export const LayoutDashboard = createIcon('Squares2X2Icon');
export const LayoutList = createIcon('QueueListIcon');
export const LifeBuoy = createIcon('LifebuoyIcon');
export const LineChart = createIcon('ChartBarSquareIcon');
export const Loader2 = createIcon('ArrowPathIcon');
export const LogOut = createIcon('ArrowLeftStartOnRectangleIcon');
export const Mail = createIcon('EnvelopeIcon');
export const MapPin = createIcon('MapPinIcon');
export const Menu = createIcon('Bars3Icon');
export const MessageCircle = createIcon('ChatBubbleLeftRightIcon');
export const MessageSquare = createIcon('ChatBubbleBottomCenterTextIcon');
export const MessageSquareText = createIcon('ChatBubbleBottomCenterTextIcon');
export const Minus = createIcon('MinusIcon');
export const Moon = createIcon('MoonIcon');
export const MoreVertical = createIcon('EllipsisVerticalIcon');
export const Package = createIcon('ArchiveBoxIcon');
export const Percent = createIcon('PercentBadgeIcon');
export const QuestionMarkCircle = createIcon('QuestionMarkCircleIcon');
export const PackagePlus = createIcon('ArchiveBoxIcon');
export const PanelLeft = createIcon('SidebarLeftIcon');
export const Pencil = createIcon('PencilIcon');
export const Phone = createIcon('PhoneIcon');
export const PhoneCall = createIcon('PhoneArrowUpRightIcon');
export const Plus = createIcon('PlusIcon');
export const PlusCircle = createIcon('PlusCircleIcon');
export const RefreshCw = createIcon('ArrowPathIcon');
export const RotateCcw = createIcon('ArrowUturnLeftIcon');
export const Save = createIcon('BookmarkSquareIcon');
export const Scale = createIcon('ScaleIcon');
export const Search = createIcon('MagnifyingGlassIcon');
export const Send = createIcon('PaperAirplaneIcon');
export const Settings = createIcon('Cog6ToothIcon');
export const ShieldAlert = createIcon('ShieldExclamationIcon');
export const ShoppingCart = createIcon('ShoppingCartIcon');
export const Sparkles = createIcon('SparklesIcon');
export const Square = createIcon('StopIcon');
export const Star = createIcon('StarIcon');
export const Sun = createIcon('SunIcon');
export const Tag = createIcon('TagIcon');
export const Target = createIcon('CursorArrowRaysIcon');
export const Trash2 = createIcon('TrashIcon');
export const TrendingDown = createIcon('ArrowTrendingDownIcon');
export const TrendingUp = createIcon('ArrowTrendingUpIcon');
export const Trophy = createIcon('TrophyIcon');
export const Truck = createIcon('TruckIcon');
export const Upload = createIcon('ArrowUpTrayIcon');
export const User = createIcon('UserIcon');
export const UserCheck = createIcon('UserCircleIcon');
export const UserPlus = createIcon('UserPlusIcon');
export const Users = createIcon('UsersIcon');
export const Wallet = createIcon('WalletIcon');
export const Wrench = createIcon('WrenchScrewdriverIcon');
export const X = createIcon('XMarkIcon');
export const XCircle = createIcon('XCircleIcon');