import { StyleSheet } from '@react-pdf/renderer'
import type { ContractPdfTheme } from './theme'

export function createDocumentStyles(theme: ContractPdfTheme) {
  return StyleSheet.create({
    page: {
      paddingTop: 124,
      paddingBottom: 58,
      paddingHorizontal: 38,
      fontSize: 9.3,
      color: theme.textStrong,
      lineHeight: 1.45,
    },
    headerContentGap: {
      height: 8,
    },
    headerWrap: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 88,
      backgroundColor: theme.primary,
      paddingHorizontal: 38,
      paddingTop: 18,
      paddingBottom: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    brandLogo: {
      width: 112,
      height: 52,
      objectFit: 'contain',
    },
    brandName: {
      color: theme.white,
      fontSize: 12,
      fontWeight: 700,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      maxWidth: 300,
    },
    documentType: {
      color: theme.white,
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 1,
      textAlign: 'right',
      marginBottom: 2,
    },
    documentNumber: {
      color: theme.white,
      fontSize: 22,
      fontWeight: 700,
      textAlign: 'right',
    },
    card: {
      marginBottom: 10,
      borderWidth: 0.8,
      borderColor: theme.border,
      backgroundColor: theme.white,
    },
    cardTitle: {
      backgroundColor: theme.light,
      color: theme.dark,
      fontSize: 8.3,
      fontWeight: 700,
      letterSpacing: 0.9,
      textTransform: 'uppercase',
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderBottomWidth: 0.8,
      borderBottomColor: theme.border,
    },
    cardBody: {
      paddingHorizontal: 10,
      paddingTop: 8,
      paddingBottom: 8,
    },
    docTitle: {
      fontSize: 12,
      fontWeight: 700,
      textTransform: 'uppercase',
      color: theme.textStrong,
      marginBottom: 8,
      letterSpacing: 0.5,
    },
    paragraph: {
      marginBottom: 4,
    },
    heading: {
      fontSize: 9,
      textTransform: 'uppercase',
      fontWeight: 700,
      marginTop: 2,
      marginBottom: 4,
      color: theme.dark,
    },
    bulletLine: {
      flexDirection: 'row',
      marginBottom: 3,
    },
    bulletDot: {
      width: 10,
      fontWeight: 700,
      color: theme.dark,
    },
    bulletText: {
      flex: 1,
    },
    partyTitle: {
      fontSize: 8,
      fontWeight: 700,
      textTransform: 'uppercase',
      color: theme.textMuted,
      marginBottom: 4,
      marginTop: 2,
    },
    signRow: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    signCol: {
      width: '46%',
    },
    signLine: {
      marginTop: 12,
      borderTopWidth: 0.8,
      borderTopColor: theme.border,
      paddingTop: 4,
      fontSize: 8,
      color: theme.textMuted,
    },
    footerWrap: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 44,
      backgroundColor: theme.footerBg,
      borderTopWidth: 0.8,
      borderTopColor: theme.border,
      paddingHorizontal: 38,
      paddingTop: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      color: theme.textMuted,
    },
    footerLeft: {
      width: '84%',
      fontSize: 7.1,
      color: theme.textMuted,
      lineHeight: 1.25,
    },
    footerRight: {
      width: '16%',
      fontSize: 8.1,
      color: theme.textMuted,
      textAlign: 'right',
      fontWeight: 700,
    },

    proposalPage: {
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 0,
      backgroundColor: '#FFFFFF',
      fontSize: 9.4,
      color: theme.textStrong,
      lineHeight: 1.4,
    },
    proposalTopBand: {
      height: 48,
      backgroundColor: theme.dark,
      paddingHorizontal: 50,
      paddingTop: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    proposalTopBandLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      maxWidth: '70%',
    },
    proposalHeaderLogo: {
      width: 64,
      height: 24,
      objectFit: 'contain',
      marginRight: 10,
    },
    proposalTopLeft: {
      color: theme.white,
      fontSize: 8.2,
      fontWeight: 700,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
    },
    proposalTopRight: {
      color: theme.white,
      fontSize: 7.4,
      maxWidth: 260,
      textAlign: 'right',
    },
    proposalTopAccent: {
      height: 3,
      backgroundColor: '#E7AF2A',
    },
    proposalPageLabel: {
      paddingHorizontal: 50,
      paddingTop: 14,
      paddingBottom: 8,
    },
    proposalPageLabelText: {
      fontSize: 8,
      fontWeight: 700,
      color: theme.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    proposalBody: {
      paddingHorizontal: 50,
      paddingTop: 14,
      paddingBottom: 68,
      flexGrow: 1,
    },
    coverTitleWrap: {
      borderWidth: 0.8,
      borderColor: theme.border,
      backgroundColor: theme.ultraLight,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 12,
    },
    coverLogo: {
      width: 120,
      height: 52,
      objectFit: 'contain',
      marginBottom: 8,
    },
    coverCompany: {
      fontSize: 11.2,
      fontWeight: 700,
      color: theme.dark,
      textTransform: 'uppercase',
      marginBottom: 8,
    },
    coverMainTitle: {
      fontSize: 21,
      fontWeight: 700,
      color: theme.dark,
      marginBottom: 8,
      lineHeight: 1.2,
    },
    coverSubtitle: {
      fontSize: 10.8,
      color: theme.primary,
      fontWeight: 700,
    },
    coverMetaGrid: {
      borderWidth: 0.8,
      borderColor: theme.border,
      marginBottom: 12,
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    coverMetaCell: {
      width: '50%',
      borderRightWidth: 0.8,
      borderBottomWidth: 0.8,
      borderRightColor: theme.border,
      borderBottomColor: theme.border,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    coverMetaLabel: {
      fontSize: 7.1,
      color: theme.textMuted,
      textTransform: 'uppercase',
      marginBottom: 2,
      fontWeight: 700,
      letterSpacing: 0.5,
    },
    coverMetaValue: {
      fontSize: 9,
      color: theme.textStrong,
      lineHeight: 1.35,
    },
    summaryBox: {
      borderWidth: 0.8,
      borderColor: theme.border,
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    sectionBoxTitle: {
      fontSize: 9,
      fontWeight: 700,
      color: theme.dark,
      textTransform: 'uppercase',
      letterSpacing: 0.7,
      marginBottom: 7,
    },
    proposalParagraph: {
      marginBottom: 6,
      fontSize: 9.2,
      color: theme.textStrong,
      lineHeight: 1.45,
    },
    proposalTopicSection: {
      marginBottom: 10,
    },
    proposalTopicTitle: {
      fontSize: 9,
      fontWeight: 700,
      color: theme.dark,
      marginBottom: 6,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    scopeCard: {
      borderWidth: 0.8,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 10,
      backgroundColor: '#FFFFFF',
    },
    proposalBulletLine: {
      flexDirection: 'row',
      marginBottom: 5,
    },
    proposalBulletDot: {
      width: 12,
      fontSize: 9.2,
      color: theme.dark,
      fontWeight: 700,
    },
    proposalBulletText: {
      flex: 1,
      fontSize: 9.2,
      color: theme.textStrong,
      lineHeight: 1.45,
    },
    priceHighlightBox: {
      backgroundColor: theme.dark,
      borderWidth: 0.8,
      borderColor: theme.dark,
      paddingVertical: 12,
      paddingHorizontal: 12,
      marginBottom: 12,
      alignItems: 'center',
    },
    priceHighlightLabel: {
      color: theme.white,
      textTransform: 'uppercase',
      fontSize: 8.2,
      letterSpacing: 0.8,
      marginBottom: 6,
      fontWeight: 700,
    },
    priceHighlightValue: {
      color: '#E7AF2A',
      fontSize: 34,
      fontWeight: 700,
      lineHeight: 1.1,
    },
    priceTable: {
      borderWidth: 0.8,
      borderColor: theme.border,
      marginBottom: 12,
    },
    priceTableHeader: {
      flexDirection: 'row',
      backgroundColor: theme.primary,
      paddingVertical: 7,
      paddingHorizontal: 10,
    },
    priceTableHeaderColA: {
      width: '60%',
      fontSize: 8.1,
      color: theme.white,
      textTransform: 'uppercase',
      fontWeight: 700,
      letterSpacing: 0.7,
    },
    priceTableHeaderColB: {
      width: '40%',
      fontSize: 8.1,
      color: theme.white,
      textTransform: 'uppercase',
      fontWeight: 700,
      letterSpacing: 0.7,
      textAlign: 'right',
    },
    priceTableRow: {
      flexDirection: 'row',
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderTopWidth: 0.8,
      borderTopColor: theme.border,
    },
    priceTableColA: {
      width: '60%',
      fontSize: 9,
      color: theme.textStrong,
      lineHeight: 1.35,
    },
    priceTableColB: {
      width: '40%',
      fontSize: 9,
      color: theme.primary,
      fontWeight: 700,
      textAlign: 'right',
      lineHeight: 1.35,
    },
    scheduleTable: {
      borderWidth: 0.8,
      borderColor: theme.border,
      marginBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    scheduleHeader: {
      flexDirection: 'row',
      backgroundColor: theme.dark,
      paddingVertical: 7,
      paddingHorizontal: 10,
    },
    scheduleHeaderColA: {
      width: '36%',
      fontSize: 8.1,
      color: theme.white,
      textTransform: 'uppercase',
      fontWeight: 700,
      letterSpacing: 0.7,
    },
    scheduleHeaderColB: {
      width: '64%',
      fontSize: 8.1,
      color: theme.white,
      textTransform: 'uppercase',
      fontWeight: 700,
      letterSpacing: 0.7,
    },
    scheduleRow: {
      flexDirection: 'row',
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderTopWidth: 0.8,
      borderTopColor: theme.border,
    },
    scheduleColA: {
      width: '36%',
      fontSize: 9,
      fontWeight: 700,
      color: theme.textStrong,
      lineHeight: 1.35,
    },
    scheduleColB: {
      width: '64%',
      fontSize: 9,
      color: theme.textStrong,
      lineHeight: 1.35,
    },
    proposalFooterAccent: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 30,
      height: 3,
      backgroundColor: '#E7AF2A',
    },
    proposalFooterBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 30,
      backgroundColor: theme.dark,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 50,
    },
    proposalFooterLeft: {
      color: theme.white,
      fontSize: 7,
    },
    proposalFooterRight: {
      color: theme.white,
      fontSize: 7,
      fontWeight: 700,
    },
  })
}

